# Generated by Django 5.1.3 on 2024-11-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
