# Generated by Django 5.1.3 on 2024-11-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caratula', models.ImageField(upload_to='projects/thumbnails/')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['orden']},
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='active',
            new_name='estatus',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='order',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='title',
            new_name='titulo',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='projects/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cip_main.project')),
            ],
        ),
    ]
