# Generated by Django 5.1.3 on 2024-12-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0003_project_alter_slide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Imagen del proyecto', 'verbose_name_plural': 'Imágenes del proyecto'},
        ),
        migrations.AddField(
            model_name='project',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='cip_main.category'),
        ),
    ]
