# Generated by Django 5.1.3 on 2024-12-03 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0004_category_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen_caratula', models.ImageField(upload_to='imagenes_productos/', verbose_name='Imagen de Carátula')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('destacado', models.BooleanField(default=False, verbose_name='Producto Destacado')),
            ],
        ),
        migrations.AddField(
            model_name='projectimage',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='cip_main.producto', verbose_name='Producto asociado'),
        ),
    ]
