# Generated by Django 5.1.3 on 2024-12-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0005_producto_projectimage_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='producto',
        ),
        migrations.AddField(
            model_name='project',
            name='producto_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='cip_main.producto', verbose_name='Producto asociado'),
        ),
    ]
