# Generated by Django 5.1.3 on 2024-12-05 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0008_servicio_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='cip_main.servicio', verbose_name='Servicio asociado'),
        ),
    ]
