# Generated by Django 5.1.3 on 2024-12-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_main', '0009_slide_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos/'),
        ),
    ]
